### ISSUE TITLE
Discovered services are never removed from MeaModDiscovery.GetOSC[Query]Services

### ISSUE THREAD

**Issue by knah** [vrchat-community/vrc-oscquery-lib#41]
There appears to be no code to remove stale services in the current implementation, resulting in services staying in the list forever, even if they are gone. This may also prevent services that change their IP or port number but not name from being correctly updated.

Looks like this is being worked on in `feature/add-disconnects` branch, but I'll create the issue nonetheless to track the issue publicly.

Additionally, it appears that the VRChat client is also not removing stale services - during my testing I saw it sending out avatar parameter data to very much dead endpoints.

**Comment by momo-the-monster** [comment]
@knah - that's correct. There is no existing mechanism for this I could find - I did start working on it in that branch but the work is incomplete and not currently roadmapped. However, if you come up with a working solution, feel free to submit a PR - thanks!

**Comment by joreg** [comment]
https://github.com/vrchat-community/vrc-oscquery-lib/pull/54 fixes this issue. being not very familiar with zeroconf i'm not entirely sure if the implementation is correct. but my local tests showed services being removed with this fix applied.
